### ISSUE TITLE
Invalid Links for ProfitBricks SDK for Ruby

### ISSUE THREAD

**Issue by jbuchhammer** [profitbricks/profitbricks-sdk-ruby#11]
### wrong target for github Link of SDK for Ruby
On https://devops.profitbricks.com/libraries/ruby/, section 'Additional Documentation and Support' the link to github points to StackPointCloud repository.
The link target must be https://github.com/profitbricks/profitbricks-sdk-ruby instead.

### dead link to ProfitBricks SDK for Ruby in Readme
In Readme.md, section [Documentation and Support](https://github.com/StackPointCloud/profitbricks-sdk-ruby#documentation-and-support) the link to 'ProfitBricks SDK for Ruby guide' is dead.

**Comment by edevenport** [comment]
The documentation links have been corrected.
