### ISSUE TITLE
Failed operations polled forever

### ISSUE THREAD

**Issue by botchniaque** [profitbricks/profitbricks-sdk-ruby#5]
`wait_for` mechanism expects success, so whenever error occurs it polls forever.

problematic code https://github.com/profitbricks/profitbricks-sdk-ruby/blob/master/lib/profitbricks/model.rb#L20

I know nothing about `Ruby`, but something like this would solve the problem:

```
    def ready?
      status = ProfitBricks::Request.get(self.requestId).status
      if status.metadata['status'] == 'FAILED'
           raise 'Operation Failed:' + status.metadata['message']
      status.metadata['status'] == 'DONE'
    end
```

**Comment by edevenport** [comment]
@botchniaque I have released a new gem version that includes the above fix.
