### ISSUE TITLE
call to create a storage volume shows failed, even if the volume is attached successfully

### ISSUE THREAD

**Issue by baldwinSPC** [profitbricks/profitbricks-sdk-ruby#7]
= The function being used

def createServer(datacenterId, name, cores, ram, availability_zone = nil)
if (availability_zone != nil)
server = ProfitBricks::Datacenter.get(datacenterId).create_server(name:
name, cores: cores, ram: ram \* 1024, availabilityZone: availability_zone)
server.wait_for { ready? }
else
server = ProfitBricks::Datacenter.get(datacenterId).create_server(name:
name, cores: cores, ram: ram \* 1024)
server.wait_for { ready? }
end
return server
end

= This function is executed via

cloud_server = createServer(cloud_datacenter.id, server.name, server.cores,
server.ram, server.availabilityZone)

server.wait_for { ready? }
# ...

status = ProfitBricks::Request.get(self.requestId).status
# ...

def get(request_id)
response = ProfitBricks.request(
method: :get,
path: "/requests/#{request_id}",
expects: 200
)
instantiate_objects(response)
end
# ...
# Construct Ruby objects from API response.

def self.instantiate_objects(response)
if response['type'] == 'collection'
response['items'].map { |item| new(item) }
else
new(response)
end
end

= If the response it no collection nor singular object but an array than the error occurs in the exceuted function
"undefined method

**Comment by nurfet-becirevic** [comment]
This is the same issue as this [one](https://github.com/profitbricks/profitbricks-sdk-ruby/issues/15). 
I think you can close it, @edevenport
